from kafka import KafkaConsumer
#from kafka import KafkaProducer
import urllib2, urllib
import json
import csv
import ast
import nltk
import logging

consumer = KafkaConsumer('test-topic', bootstrap_servers='localhost:9092')

def noiseRemoval(rawWordList):
    try:
        noise_list=['CHAIYE', 'THE', 'AND', 'A', 'TO', 'OF', 'IN', 'I', 'IS', 'THAT', 'IT', 'ON', 'YOU', 'THIS', 'FOR', 'BUT', 'WITH', 'ARE', 'HAVE', 'BE', 'AT', 'OR', 'AS', 'WAS', 'SO', 'IF', 'OUT', 'NOT', 'ADDRESS', 'HAAN', 'KYA', 'PHIRAUR', 'HAANJI', 'LE', 'SAUBAS', 'LIJIYE', 'THEEKBHEJOON', 'LIKH', 'BHEJTA', 'HARI', 'LO', 'WALA', 'BHI', 'HELLO', 'MADAM', 'WINGCHAHIYE', 'HOON', 'MAM', 'WOHDENA', 'KA', 'NA', 'WOHIDO', 'KAUNSA', 'NAHIN', 'YAKOI', 'OM', 'YEH']
        noise_free_words = [word for word in rawWordList if word not in noise_list]
        return noise_free_words
    except Exception as err:
        print('Error 001: Error in noiseRemoval function '+str(err))
def selectItems(cleanWordList):
    try:
        menu=['JEERA MILAGU RASAM SOUP', 'TAKALIKOTAMLLI RASAM SOUP', 'LEMON RASAM SOUP', 'RAVA UPMA', 'SEMIYA UPMA', 'MEDU VADA', 'ONION MEDU VADA', 'RASAM VADA', 'DAHI VADA', 'POORI BHAJI', 'POORI WITH KORMA', 'ALOO JEERA', 'SABUDANA VADA', 'STEAMED IDLI', 'BUTTER STEAMED IDLI', 'IDLI VADA SAMBAR', 'MINI MULGAPODI IDLI', 'KANCHEEPURAM IDLI', 'MINI CRISPY POWDER IDLI', 'MINI FRIED MASALA IDLI', 'JAIN MINI FRIED MASALA IDLI', 'BUTTER GARLIC IDLI', 'MADRASI FRIED IDLI', 'JAIN MADRASI FRIED IDLI', 'BANGALORE STYLE IDLI CHILLI', 'IDLI PORIYAL', 'MAHABALIPURAM PUDINA IDLI', 'ANDHRA STYLE IDLI CHILLI', 'MOORUKOLAMBU IDLI', 'JAIN MOORUKOLAMBU IDLI', 'HYDERABADI CURRY IDLI', 'KAIMA IDLI', 'MYSORE KOTHU IDLI', 'KERALA STYLE TADKA IDLI', 'CHETTINADU VEGETABLE IDLI', 'IDLI GHASI', 'DINDIGUL THALAPAKATTU IDLI', 'ACHARI ONION MASALA IDLI', 'KERALA SPECIAL STEAMED RICE PUTTU', 'BALAJI SPECIAL IDLI PLATTER', 'CHINESE FUSION IDLIS', 'CHILLI GARLIC IDLI', 'CHINESE STYLE IDLI CHILLI DRY', 'IDLI MANCHURIAN IN SOYA SAUCE', 'SCHEZWAN IDLI CHILLI', 'SADA DOSA', 'CHEESE SADA DOSA', 'UDUPI MASALA DOSA', 'CHEESE UDUPI MASALA DOSA', 'MYSORE SADA DOSA', 'CHEESE MYSORE SADA DOSA', 'MYSORE MASALA DOSA', 'CHEESE MYSORE MASALA DOSA', 'GHEE PODI ROAST DOSA', 'CHETTINADU STYLE DOSA', 'ROYAL DAKSHIN DOSA', 'ROYAL SALAD DOSA', 'ACHARI ONION MASALA DOSA', 'MADRAS AVIAL DOSA', 'GHEE MANGALOREAN DOSA', 'ROASTED ONION CHEESE DOSA', 'ROASTED CHEESE GARLIC DOSA', 'METHI GARLIC CHEESE DOSA', 'PANEER CHATPATA', 'PANEER SUKHA DOSA', 'SPICY CHILLI POTATO DOSA', 'PAV BHAJI DOSA', 'CHEESE PAV BHAJI DOSA', 'PALAK CHEESE GARLIC DOSA', 'PALAK PANEER DOSA', 'CHEESE POTATO DOSA', 'ALOO PALAK DOSA', 'RAGI UDUPI MASALA DOSA', 'AMERICAN CHEESE CORN DOSA', 'PAPER SADA DOSA', 'CHEESE PAPER SADA DOSA', 'PAPER MASALA DOSA', 'CHEESE PAPER MASALA DOSA', 'KANCHEEPURAM PAPER ROAST DOSA', 'KANCHEEPURAM PAPER ROAST CHEESE GARLIC DOSA', 'PANEER CHEESE CAPSICUM DOSA', 'BALAJI SPECIAL PANEER BHURJI DOSA', 'SPRING ROLL DOSA', 'SPRING ROLL DOSA WITH CHEESE', 'PANEER CHILLI DOSA', 'PANEER CHILLI DOSA WITH CHEESE', 'PANEER SCHEZWAN DOSA', 'MANCHURIAN DOSA', 'MANCHURIAN DOSA WITH CHEESE', 'PANEER MANCHURIAN DOSA', 'SCHEZWAN MANCHURIAN CHEESE DOSA', 'ROASTED CHILLI GARLIC SCHEZWAN DOSA', 'PANEER MUSHROOM SCHEZWAN DOSA', 'RAVA SADA DOSA', 'BUTTER RAVA SADA DOSA', 'CHEESE RAVA SADA DOSA', 'RAVA UDUPI MASALA DOSA', 'BUTTER RAVA UDUPI MASALA DOSA', 'CHEESE RAVA UDUPI MASALA DOSA', 'ONION RAVA SADA DOSA', 'BUTTER ONION RAVA SADA DOSA', 'CHEESE ONION RAVA SADA DOSA', 'ONION RAVA MASALA DOSA', 'BUTTER ONION RAVA MASALA DOSA', 'CHEESE ONION RAVA MASALA DOSA', 'BALAJI SPECIAL KERALA RAVA DOSA', 'BUTTER SOFT UTTAPAM', 'VEGETABLE BUTTER SOFT UTTAPAM', 'PANEER UTTAPAM', 'CHEESE UTTAPAM', 'MASALA UTTAPAM', 'TOMATO UTTAPAM', 'ONION UTTAPAM', 'TOMATO ONION UTTAPAM', 'TOMATO ONION CHEESE UTTAPAM', 'CHEESE CAPSICUM UTTAPAM', 'ALOO METHI UTTAPAM', 'METHI GARLIC UTTAPAM', 'CORIANDER JEERA UTTAPAM', 'ROASTED CHILLI GARLIC UTTAPAM', 'KANCHEEPURAM MASALA UTTAPAM', 'CHEESE CHILLI GARLIC UTTAPAM', 'PAV BHAJI CHEESE UTTAPAM', 'AMERICAN CHEESE CORN UTTAPAM', 'COCONUT HONEY UTTAPAM', 'SANDWICH UTTAPAM', 'CHEESE SANDWICH UTTAPAM', 'ASSORTED UTTAPAMS.', 'APPAM WITH COCONUT MILK', 'APPAM WITH VEGETABLE STEW', 'APPAM WITH VEGETABLE KORMA', 'APPAM WITH VEGETABLE CHETTINADU MASALA', 'APPAM WITH PANEER GHASI', 'APPAM WITH KERALA MALLIPURAM GRAVY', 'APPAM WITH SOYA POTATO CURRY MASALA', 'APPAM WITH VEGETABLE HYDERABADI MASALA', 'NEER DOSA WITH SAMBAR', 'NEER DOSA WITH SWEET CHUTNEY', 'NEER DOSA WITH VEGETABLE KORMA', 'NEER DOSA WITH VEGETABLE GHASI', 'NEER DOSA WITH VEGETABLE CHETTINADU MASALA', 'NEER DOSA WITH VEGETABLE PALAK PANEER', 'MASALA PANIYARRAM WITH SAMBAR', 'SWEET PANIYARRAM WITH GUD CHUTNEY', 'BISIBELE BHATH', 'LEMON RICE', 'TOMATO RICE', 'RASAM RICE', 'CURD RICE', 'SAMBAR RICE', 'BALAJI SPECIAL COCONUT RICE', 'BALAJI SPECIAL IMLI RICE', 'CALICUT PULAO', 'HYDERABADI BIRYANI', 'CHETTINADU BIRYANI', 'PAV BHAJI', 'JAIN PAV BHAJI', 'CHEESE PAV BHAJI', 'PANEER PAV BHAJI', 'BALAJI SPECIAL PAV BHAJI', 'CREAM OF MUSHROOM SOUP', 'CREAM OF VEGETABLE SOUP', 'MANCHOW SOUP', 'HOT & SOUR CLEAR SOUP', 'SWEET CORN SOUP', 'LEMON CORIANDER SOUP', 'BURNT GARLIC SOUP', 'VEG CLEAR SOUP', 'PANEER TIKKA', 'PANEER PUDINA TIKKA', 'PANEER ACHARI TIKKA', 'PANEER MALAI TIKKA', 'PANEER LEHSUNI KEBAB', 'PANEER CHEESE KEBAB', 'HARA BHARA KEBAB', 'VEG SEEKH KEBAB', 'STUFFED TANDOORI ALOO TIKKA', 'STUFFED MUSHROOM TIKKA', 'MUSHROOM ACHARI TIKKA', 'VEGETABLE KEBAB PLATTER', 'PANEER KEBAB PLATTER', 'ALOO MATTAR', 'ALOO GOBI', 'ALOO METHI', 'KOLHAPURI SABJI', 'TAWA SABJI', 'JAIN TAWA SABJI', 'MIXED SABJI MASALA', 'JAIN MIXED SABJI MASALA', 'SABJI MAKHANWALA', 'JAIN SABJI MAKHANWALA', 'SABJI LAJORI', 'AMRITSARI SABJI MASALA', 'HYDERABADI SABJI MASALA', 'CHILLI MILLI KOFTA', 'MALAI KOFTA', 'MAKHMALAI KOFTA', 'METHI MATTAR MALAI', 'MUSHROOM KADAI', 'MUSHROOM HANDI', 'BABY CORN MUSHROOM MASALA', 'PALAK PANEER', 'MATTAR PANEER', 'COTTAGE CHEESE CUBES COOKED IN RED GRAVY.', 'PANEER BUTTER MASALA', 'PANEER MAKHANWALA', 'JAIN PANEER MAKHANWALA', 'PANEER PASANDA', 'JAIN PANEER PASANDA', 'PANEER LEHSUNI', 'PANEER CHATPATA', 'JAIN PANEER CHATPATA', 'PANEER PATIALA', 'PANEER KADAI', 'JAIN PANEER KADAI', 'PANEER KOLHAPURI', 'PANEER MAKHANI', 'PANEER HYDERABADI MASALA', 'PANEER HILLTOP MASALA', 'PANEER MUSHROOM MASALA', 'PANEER MUSHROOM BABY CORN MASALA', 'JEERA RICE', 'VEGETABLE PULAO', 'PEAS PULAO', 'KASHMIRI PULAO', 'VEG BIRYANI', 'DAL FRY', 'DAL TADKA', 'TANDOORI ROTI', 'BUTTER ROTI', 'NAAN', 'BUTTER NAAN', 'CHEESE NAAN', 'GARLIC NAAN', 'KULCHA', 'BUTTER KULCHA', 'STEAMED RICE', 'SINGLE APPAM', 'CHEESE APPAM', 'NEER DOSA', 'POORI', 'CHAPATI', 'SAMBAR', 'CURD', 'ROASTED PAPAD', 'FRIED PAPAD', 'MASALA PAPAD', 'MIXED VEG RAITA', 'BOONDI RAITA', 'PINEAPPLE RAITA', 'VEG FRIED RICE', 'VEG SCHEZWAN FRIED RICE', 'VEG TRIPLE SCHEZWAN FRIED RICE', 'VEG HONG KONG RICE', 'VEG SINGAPORE FRIED RICE', 'MUSHROOM FRIED RICE', 'PANEER FRIED RICE', 'VEG BURNT CHILLI GARLIC FRIED RICE', 'VEG HAKKA NOODLES', 'VEG SCHEZWAN NOODLES', 'VEG TRIPLE SCHEZWAN NOODLES', 'VEG CHILLI GARLIC BURNT NOODLES', 'VEG MANCHURIAN GRAVY', 'PANEER MANCHURIAN GRAVY', 'MUSHROOM MANCHURIAN GRAVY', 'PANEER CHILLI GRAVY', 'BROCCOLI & MUSHROOM IN MANCHURIAN GRAVY', 'CHILLI GARLIC BURNT VEGETABLE HONG KONG STYLE', 'GULAB JAMUN', 'PINEAPPLE SHEERA', 'SEMIYA PAYASAM', 'ORANGE JUICE', 'MOSAMBI JUICE', 'MARA MARI JUICE', 'WATERMELON JUICE', 'PINEAPPLE JUICE', 'MADRAS FILTER COFFEE', 'BALAJI SPECIAL TEA', 'BUTTERMILK', 'FRESH LIME SODA', 'SWEET LASSI', 'DRY FRUIT LASSI']
        dishCount=0
        orderItemList=[]
        for dish in menu:
            dishBreakUp=dish.split(' ')
            dishAdded=False
            dishCount=dishCount+1
            print("Searching for item no."+str(dishCount)+": "+dish)
            for i in range(len(cleanWordList)):
                if dishAdded==False:
                    if cleanWordList[i] in dishBreakUp:
                        if len(dishBreakUp)==0:
                            print("Invalid Case")
                            break
                        elif len(dishBreakUp)>1:
                            rawGuessDish=cleanWordList[i:(i+len(dishBreakUp))]
                            print(rawGuessDish)
                            if set(rawGuessDish).intersection(set(dishBreakUp))==set(dishBreakUp):
                                orderItemList.append(dish)
                                dishAdded=True
                        else:
                            cleanWordList[i]==dishBreakUp
                            orderItemList.append(dish)
                            dishAdded=True
                    else:
                        print("Word: "+cleanWordList[i]+" did not matched for item: "+dish)
                        continue
                else:
                    break
        print("orderItemList",orderItemList)
        return(orderItemList)
    except Exception as err:
        print('Error 002: Error in selectItems function ' + str(err))
def checkordereditems(ordereditems):
    try:

        FinalOrdereditems=[]
        if len(ordereditems)==1:
            FinalOrdereditems = []
        elif len(ordereditems)>1:
            for i in range(len(ordereditems)-1):
                itemOneRemoved = False
                itemOne=ordereditems[i]
                for itemTwo in ordereditems[i+1:]:
                    if itemOneRemoved == False :
                        print(itemTwo)
                        if (len(itemOne.split(' '))<len(itemTwo.split(' '))) and(set(itemOne.split(' ')).intersection(set(itemTwo.split(' ')))==set(itemOne.split(' '))):
                            FinalOrdereditems.append(itemOne)
                            itemOneRemoved = True
                        elif (len(itemTwo.split(' '))<len(itemOne.split(' '))) and(set(itemTwo.split(' ')).intersection(set(itemOne.split(' ')))==set(itemTwo.split(' '))):
                            FinalOrdereditems.append(itemOne)
                            itemOneRemoved = True
        else:
            print("invalidCase")
            FinalOrdereditems=[]
        FinalOutputOrdereditems = [item for item in set(ordereditems) - set(FinalOrdereditems)]
        print(FinalOutputOrdereditems)
        return(FinalOutputOrdereditems)

    except Exception as err:
        print('Error 003: Error in checkordereditems function ' + str(err))

def createOrder(finalordereditems,Identity,quantity):
    try:
        ratelist = {'JEERA MILAGU RASAM SOUP': 100, 'TAKALIKOTAMLLI RASAM SOUP': 100, 'LEMON RASAM SOUP': 100, 'RAVA UPMA': 75, 'SEMIYA UPMA': 100, 'MEDU VADA': 80, 'ONION MEDU VADA': 100, 'RASAM VADA': 100, 'DAHI VADA': 100, 'POORI BHAJI (5 PCS)': 130, 'POORI WITH KORMA (5 PCS)': 160, 'ALOO JEERA': 75, 'SABUDANA VADA': 80, 'STEAMED IDLI': 60, 'BUTTER STEAMED IDLI': 75, 'IDLI VADA SAMBAR': 70, 'MINI MULGAPODI IDLI': 90, 'KANCHEEPURAM IDLI': 100, 'MINI CRISPY POWDER IDLI': 120, 'MINI FRIED MASALA IDLI': 140, 'JAIN MINI FRIED MASALA IDLI': 140, 'BUTTER GARLIC IDLI': 140, 'MADRASI FRIED IDLI': 160, 'JAIN MADRASI FRIED IDLI': 160, 'BANGALORE STYLE IDLI CHILLI': 170, 'IDLI PORIYAL': 170, 'MAHABALIPURAM PUDINA IDLI': 170, 'ANDHRA STYLE IDLI CHILLI': 170, 'MOORUKOLAMBU IDLI': 170, 'JAIN MOORUKOLAMBU IDLI': 170, 'HYDERABADI CURRY IDLI': 170, 'KAIMA IDLI': 170, 'MYSORE KOTHU IDLI': 170, 'KERALA STYLE TADKA IDLI': 170, 'CHETTINADU VEGETABLE IDLI': 170, 'IDLI GHASI': 175, 'DINDIGUL THALAPAKATTU IDLI': 175, 'ACHARI ONION MASALA IDLI': 175, 'KERALA SPECIAL STEAMED RICE PUTTU': 175, 'BALAJI SPECIAL IDLI PLATTER': 225, 'CHINESE FUSION IDLIS': 175, 'CHILLI GARLIC IDLI': 175, 'CHINESE STYLE IDLI CHILLI DRY': 175, 'IDLI MANCHURIAN IN SOYA SAUCE': 175, 'SCHEZWAN IDLI CHILLI': 175, 'SADA DOSA': 80, 'CHEESE SADA DOSA': 110, 'UDUPI MASALA DOSA': 100, 'CHEESE UDUPI MASALA DOSA': 130, 'MYSORE SADA DOSA': 90, 'CHEESE MYSORE SADA DOSA': 120, 'MYSORE MASALA DOSA': 110, 'CHEESE MYSORE MASALA DOSA': 140, 'GHEE PODI ROAST DOSA': 110, 'CHETTINADU STYLE DOSA': 140, 'ROYAL DAKSHIN DOSA': 160, 'ROYAL SALAD DOSA': 160, 'ACHARI ONION MASALA DOSA': 160, 'MADRAS AVIAL DOSA': 160, 'GHEE MANGALOREAN DOSA': 160, 'ROASTED ONION CHEESE DOSA': 170, 'ROASTED CHEESE GARLIC DOSA': 170, 'METHI GARLIC CHEESE DOSA': 170, 'PANEER CHATPATA': 190, 'PANEER SUKHA DOSA': 170, 'SPICY CHILLI POTATO DOSA': 160, 'PAV BHAJI DOSA': 140, 'CHEESE PAV BHAJI DOSA': 170, 'PALAK CHEESE GARLIC DOSA': 170, 'PALAK PANEER DOSA': 170, 'CHEESE POTATO DOSA': 170, 'ALOO PALAK DOSA': 160, 'RAGI UDUPI MASALA DOSA': 140, 'AMERICAN CHEESE CORN DOSA': 170, 'PAPER SADA DOSA': 170, 'CHEESE PAPER SADA DOSA': 200, 'PAPER MASALA DOSA': 200, 'CHEESE PAPER MASALA DOSA': 230, 'KANCHEEPURAM PAPER ROAST DOSA': 200, 'KANCHEEPURAM PAPER ROAST CHEESE GARLIC DOSA': 230, 'PANEER CHEESE CAPSICUM DOSA': 200, 'BALAJI SPECIAL PANEER BHURJI DOSA': 220, 'SPRING ROLL DOSA': 150, 'SPRING ROLL DOSA WITH CHEESE': 180, 'PANEER CHILLI DOSA': 170, 'PANEER CHILLI DOSA WITH CHEESE': 190, 'PANEER SCHEZWAN DOSA': 170, 'MANCHURIAN DOSA': 150, 'MANCHURIAN DOSA WITH CHEESE': 180, 'PANEER MANCHURIAN DOSA': 170, 'SCHEZWAN MANCHURIAN CHEESE DOSA': 170, 'ROASTED CHILLI GARLIC SCHEZWAN DOSA': 170, 'PANEER MUSHROOM SCHEZWAN DOSA': 180, 'RAVA SADA DOSA': 90, 'BUTTER RAVA SADA DOSA': 105, 'CHEESE RAVA SADA DOSA': 120, 'RAVA UDUPI MASALA DOSA': 100, 'BUTTER RAVA UDUPI MASALA DOSA': 115, 'CHEESE RAVA UDUPI MASALA DOSA': 130, 'ONION RAVA SADA DOSA': 100, 'BUTTER ONION RAVA SADA DOSA': 115, 'CHEESE ONION RAVA SADA DOSA': 130, 'ONION RAVA MASALA DOSA': 110, 'BUTTER ONION RAVA MASALA DOSA': 125, 'CHEESE ONION RAVA MASALA DOSA': 140, 'BALAJI SPECIAL KERALA RAVA DOSA': 170, 'BUTTER SOFT UTTAPAM': 90, 'VEGETABLE BUTTER SOFT UTTAPAM': 110, 'PANEER UTTAPAM': 100, 'CHEESE UTTAPAM': 100, 'MASALA UTTAPAM': 100, 'TOMATO UTTAPAM': 100, 'ONION UTTAPAM': 100, 'TOMATO ONION UTTAPAM': 110, 'TOMATO ONION CHEESE UTTAPAM': 110, 'CHEESE CAPSICUM UTTAPAM': 140, 'ALOO METHI UTTAPAM': 140, 'METHI GARLIC UTTAPAM': 140, 'CORIANDER JEERA UTTAPAM': 140, 'ROASTED CHILLI GARLIC UTTAPAM': 140, 'KANCHEEPURAM MASALA UTTAPAM': 140, 'CHEESE CHILLI GARLIC UTTAPAM': 150, 'PAV BHAJI CHEESE UTTAPAM': 170, 'AMERICAN CHEESE CORN UTTAPAM': 160, 'COCONUT HONEY UTTAPAM': 170, 'SANDWICH UTTAPAM': 150, 'CHEESE SANDWICH UTTAPAM': 180, 'ASSORTED UTTAPAMS.': 225, 'APPAM WITH COCONUT MILK': 150, 'APPAM WITH VEGETABLE STEW': 175, 'APPAM WITH VEGETABLE KORMA': 175, 'APPAM WITH VEGETABLE CHETTINADU MASALA': 175, 'APPAM WITH PANEER GHASI': 175, 'APPAM WITH KERALA MALLIPURAM GRAVY': 175, 'APPAM WITH SOYA POTATO CURRY MASALA': 175, 'APPAM WITH VEGETABLE HYDERABADI MASALA': 175, 'NEER DOSA WITH SAMBAR': 100, 'NEER DOSA WITH SWEET CHUTNEY': 120, 'NEER DOSA WITH VEGETABLE KORMA': 150, 'NEER DOSA WITH VEGETABLE GHASI': 150, 'NEER DOSA WITH VEGETABLE CHETTINADU MASALA': 150, 'NEER DOSA WITH VEGETABLE PALAK PANEER': 175, 'MASALA PANIYARRAM WITH SAMBAR': 100, 'SWEET PANIYARRAM WITH GUD CHUTNEY': 120, 'BISIBELE BHATH': 180, 'LEMON RICE': 170, 'TOMATO RICE': 170, 'RASAM RICE': 170, 'CURD RICE': 170, 'SAMBAR RICE': 170, 'BALAJI SPECIAL COCONUT RICE': 180, 'BALAJI SPECIAL IMLI RICE': 180, 'CALICUT PULAO': 180, 'HYDERABADI BIRYANI': 190, 'CHETTINADU BIRYANI': 190, 'PAV BHAJI': 110, 'JAIN PAV BHAJI': 120, 'CHEESE PAV BHAJI': 130, 'PANEER PAV BHAJI': 130, 'BALAJI SPECIAL PAV BHAJI': 150, 'CREAM OF MUSHROOM SOUP': 90, 'CREAM OF VEGETABLE SOUP': 90, 'MANCHOW SOUP': 100, 'HOT & SOUR CLEAR SOUP': 100, 'SWEET CORN SOUP': 100, 'LEMON CORIANDER SOUP': 100, 'BURNT GARLIC SOUP': 100, 'VEG CLEAR SOUP': 100, 'PANEER TIKKA': 190, 'PANEER PUDINA TIKKA': 190, 'PANEER ACHARI TIKKA': 190, 'PANEER MALAI TIKKA': 190, 'PANEER LEHSUNI KEBAB': 190, 'PANEER CHEESE KEBAB': 210, 'HARA BHARA KEBAB': 175, 'VEG SEEKH KEBAB': 175, 'STUFFED TANDOORI ALOO TIKKA': 175, 'STUFFED MUSHROOM TIKKA': 190, 'MUSHROOM ACHARI TIKKA': 190, 'VEGETABLE KEBAB PLATTER': 250, 'PANEER KEBAB PLATTER': 300, 'ALOO MATTAR': 160, 'ALOO GOBI': 160, 'ALOO METHI': 160, 'KOLHAPURI SABJI': 170, 'TAWA SABJI': 170, 'JAIN TAWA SABJI': 170, 'MIXED SABJI MASALA': 180, 'JAIN MIXED SABJI MASALA': 180, 'SABJI MAKHANWALA': 180, 'JAIN SABJI MAKHANWALA': 180, 'SABJI LAJORI': 180, 'AMRITSARI SABJI MASALA': 180, 'HYDERABADI SABJI MASALA': 180, 'CHILLI MILLI KOFTA': 190, 'MALAI KOFTA': 190, 'MAKHMALAI KOFTA': 190, 'METHI MATTAR MALAI': 190, 'MUSHROOM KADAI': 190, 'MUSHROOM HANDI': 190, 'BABY CORN MUSHROOM MASALA': 190, 'PALAK PANEER': 190, 'MATTAR PANEER': 190, 'COTTAGE CHEESE CUBES COOKED IN RED GRAVY.': 190, 'PANEER BUTTER MASALA': 190, 'PANEER MAKHANWALA': 190, 'JAIN PANEER MAKHANWALA': 190, 'PANEER PASANDA': 190, 'JAIN PANEER PASANDA': 190, 'PANEER LEHSUNI': 190, 'JAIN PANEER CHATPATA': 190, 'PANEER PATIALA': 190, 'PANEER KADAI': 190, 'JAIN PANEER KADAI': 190, 'PANEER KOLHAPURI': 190, 'PANEER MAKHANI': 190, 'PANEER HYDERABADI MASALA': 190, 'PANEER HILLTOP MASALA': 225, 'PANEER MUSHROOM MASALA': 225, 'PANEER MUSHROOM BABY CORN MASALA': 225, 'JEERA RICE': 120, 'VEGETABLE PULAO': 140, 'PEAS PULAO': 140, 'KASHMIRI PULAO': 150, 'VEG BIRYANI': 180, 'DAL FRY': 110, 'DAL TADKA': 120, 'TANDOORI ROTI': 20, 'BUTTER ROTI': 25, 'NAAN': 30, 'BUTTER NAAN': 35, 'CHEESE NAAN': 45, 'GARLIC NAAN': 45, 'KULCHA': 30, 'BUTTER KULCHA': 35, 'STEAMED RICE': 100, 'SINGLE APPAM': 30, 'CHEESE APPAM': 50, 'NEER DOSA': 30, 'POORI (5 PCS)': 50, 'CHAPATI (2 PCS)': 25, 'SAMBAR': 50, 'CURD': 50, 'ROASTED PAPAD': 15, 'FRIED PAPAD': 20, 'MASALA PAPAD': 30, 'MIXED VEG RAITA': 70, 'BOONDI RAITA': 70, 'PINEAPPLE RAITA': 70, 'VEG FRIED RICE': 180, 'VEG SCHEZWAN FRIED RICE': 180, 'VEG TRIPLE SCHEZWAN FRIED RICE': 190, 'VEG HONG KONG RICE': 190, 'VEG SINGAPORE FRIED RICE': 190, 'MUSHROOM FRIED RICE': 190, 'PANEER FRIED RICE': 190, 'VEG BURNT CHILLI GARLIC FRIED RICE': 190, 'VEG HAKKA NOODLES': 180, 'VEG SCHEZWAN NOODLES': 180, 'VEG TRIPLE SCHEZWAN NOODLES': 180, 'VEG CHILLI GARLIC BURNT NOODLES': 180, 'VEG MANCHURIAN GRAVY': 190, 'PANEER MANCHURIAN GRAVY': 210, 'MUSHROOM MANCHURIAN GRAVY': 210, 'PANEER CHILLI GRAVY': 210, 'BROCCOLI & MUSHROOM IN MANCHURIAN GRAVY': 210, 'CHILLI GARLIC BURNT VEGETABLE HONG KONG STYLE': 210, 'GULAB JAMUN': 50, 'PINEAPPLE SHEERA': 80, 'SEMIYA PAYASAM': 100, 'ORANGE JUICE': 70, 'MOSAMBI JUICE': 70, 'MARA MARI JUICE': 70, 'WATERMELON JUICE': 70, 'PINEAPPLE JUICE': 70, 'MADRAS FILTER COFFEE': 30, 'BALAJI SPECIAL TEA': 25, 'BUTTERMILK': 40, 'FRESH LIME SODA': 40, 'SWEET LASSI': 80, 'DRY FRUIT LASSI': 110}
        for item in finalordereditems:
            responseItem = {'ID':  Identity, "orderItem": item,"quantity": quantity, "rate": ratelist[item], "amount": ratelist[item] * quantity}
            return(responseItem)
    except Exception as err:
        print('Error 004: Error in placeOrder function ' + str(err))

def sendOrder(Order):
    try:
        print(Order)
        mydata = [('ID', Order['ID']), ('rate', Order['rate']), ('orderItem', Order['orderItem']),('quantity',Order['quantity'])]
        mydata = urllib.urlencode(mydata)
        path = 'http://ec2-18-191-56-202.us-east-2.compute.amazonaws.com/orderly.php'  # the url you want to POST to
        req = urllib2.Request(path, mydata)
        req.add_header("Content-type", "application/x-www-form-urlencoded")
        page = urllib2.urlopen(req).read()
        return(page,"order placed sucessfully")
    except Exception as err:
        print('Error 005: Error in sendOrder function ' + str(err))

for object in consumer:
    ordereditems=[]
    word_list=[]
    response = []
    placedorder=False
    message=ast.literal_eval(object.value)
    identity=message['ID']
    conversation=message['msg'].upper()
    sentenceList=conversation.split(',')
    for sentence in sentenceList:
        rawWordList=sentence.split(' ')
        cleanWordList=noiseRemoval(rawWordList)
        ordereditems=selectItems(cleanWordList)
        finalordereditems=checkordereditems(ordereditems)
        Order=createOrder(finalordereditems,identity,quantity=1)
        sendorderStatus=sendOrder(Order)
        print(sendorderStatus)